[build]
  command = "pnpm run build"
  publish = ".next"

[[edge_functions]]
  path = "/api/generate"
  function = "generate"

[functions]
  external_node_modules = ["@node-rs/helper"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
