[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_BACKEND_URL = "https://3.83.244.93"
  NEXT_PUBLIC_WS_URL = "wss://3.83.244.93"
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"
